### ISSUE TITLE
Suggestion: darken color of symbol body fills

### ISSUE THREAD

**Issue by rjhelms** [AlexanderBrevig/kicad-gruvbox-theme#1]
Just as a friendly suggestion, there may be a benefit to some more contrast between the "symbol body fill" color and the "pin name" color - especially for big symbols with filled bodies, the pin names can be a little hard to read:

![image](https://user-images.githubusercontent.com/8541186/151081532-7ae1c007-3627-4fbb-b2ab-ee6d15dc8970.png)

For example, here is the same schematic after darkening "symbol body fills" to #584F46FF:

![image](https://user-images.githubusercontent.com/8541186/151081589-0169c679-2448-48bc-b96e-ddb20156626d.png)

**Comment by AlexanderBrevig** [comment]
Hi! I will make a new version soon. I've tweaked a few things and the body color is one of them. I will close this when the next version is up!

**Comment by AlexanderBrevig** [comment]
https://gitlab.com/kicad/addons/metadata/-/merge_requests/44

EESCHEMA         |  PCBNEW
:-------------------------:|:-------------------------:
![Gruvbox theme](https://raw.githubusercontent.com/alexanderbrevig/kicad-gruvbox-theme/main/eeschema.png)  |  ![Gruvbox theme](https://raw.githubusercontent.com/alexanderbrevig/kicad-gruvbox-theme/main/pcbnew.png)
